Fixed bugs and docs.

diff --git a/quickstart/scripts/5-register-image b/quickstart/scripts/5-register-image
--- a/quickstart/scripts/5-register-image
+++ b/quickstart/scripts/5-register-image
@@ -50,13 +50,32 @@ then
 	$nova_manage image convert "$tmp_dir"
 elif ubuntu_cloudimg? "$tmp_dir/$prefix"
 then
-	$nova_manage image all_register \
-		--image=$prefix.img \
-		--kernel=$prefix-vmlinuz-virtual \
-		--ram=$prefix-initrd-virtual \
+	#$nova_manage image all_register \
+	#	--image=$prefix.img \
+	#	--kernel=$prefix-vmlinuz-virtual \
+	#	--ram=$prefix-initrd-virtual \
+	#	--name=$prefix \
+	#	--public=T \
+	#	--arch=$(guess_arch $prefix)
+	ret=$($nova_manage image kernel_register \
+		--path=$prefix-vmlinuz-virtual \
+		--owner=admin
+		--name=$prefix-kernel \
+		--public=T \
+		--arch=$(guess_arch $prefix))
+	kid=$(echo $ret | gawk '{print $4}')
+	if ! [ $kid -gt 0 ]
+	then
+		echo "Error: register kernel image failed."
+		exit 1
+	fi
+	$nova_manage image image_register \
+		--path=$prefix.img \
+		--owner=admin
 		--name=$prefix \
 		--public=T \
 		--arch=$(guess_arch $prefix)
+		--kernel=$kid
 else
 	echo "[WARN] $0: Unkown IMAGE format, skip register image."
 fi
